version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12

  build:
    commands:
      - npm i
      - npm run boot
      - npm test
      - npm run ci:format
      - npm run ci:lint
      - npm run ci:build

cache:
  paths:
    - /root/.npm/**/*
    - /usr/local/share/.cache/**/*
