version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  build:
    commands:
      - cd ./server
      - npm i
      - npm run build
      - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - docker build -t rsschool/api:latest .
      - docker push rsschool/api:latest
      - echo "$SSH_EC2_KEY" >> key.pem && chmod 400 key.pem
      - ssh-keyscan $RSSCHOOL_API_HOST >> /root/.ssh/known_hosts
      - >
        ssh -tt -i "key.pem" $RSSCHOOL_API_EC2_USER@$RSSCHOOL_API_HOST "
          sleep 10
          docker pull rsschool/api:latest 
          docker-compose stop api
          docker-compose rm -f api
          docker-compose up -d api
          docker system prune -f "

cache:
  paths:
    - /root/.npm/**/*
    - /usr/local/share/.cache/**/*
